Fix for #326
Xilinx/RapidWright pull request #328
Opened 2022-01-19 02:47 UTC by clavin-xlnx

Signed-off-by: Chris Lavin <clavin@xilinx.com>

2022-01-19 02:50 UTC, clavin-xlnx commented
I found that originally we had to create a list of BRAM-related Cell-BEL pin mappings that were controlled by parameters set on the cell.  For Series 7, the IDDR, IDDR_CLK and ODDR were missing.  This change adds those as well as some missing from other series as well, including a number for Versal.  A DeviceResources test (creating a device Interchange representation and then verifying it) is added as well as a point test for IDDR.

2022-01-20 01:29 UTC, eddieh-xlnx requested changes

2022-01-20 01:29 UTC, eddieh-xlnx commented on test/com/xilinx/rapidwright/interchange/TestCellBELMappings.java
> +        Assertions.assertTrue(foundIDDR);
So I commented out your new `__SRVAL` addition and this test still passed. The following fails without the addition and passes with:
```suggestion
        boolean foundIDDRS = false;
        boolean foundIDDRR = false;
        for(int i=0; i < devBuilder.getCellBelMap().size(); i++) {
            CellBelMapping.Builder mapping = devBuilder.getCellBelMap().get(i);
            if(allStrings.get(mapping.getCell()).equals("IDDR")) {
                Assertions.assertTrue(mapping.hasParameterPins());
               for(ParameterCellBelPinMaps.Builder paramPins : mapping.getParameterPins()) {
                    for(CellBelPinEntry.Builder pinObj : paramPins.getPins()) {
                        Assertions.assertEquals(allStrings.get(pinObj.getBelPin()), "SR");
                        String cellPinName = allStrings.get(pinObj.getCellPin());
                        foundIDDRS = foundIDDRS || cellPinName.equals("S");
                        foundIDDRR = foundIDDRR || cellPinName.equals("R");
                    }
                }
            }
        }
        Assertions.assertTrue(foundIDDRS);
        Assertions.assertTrue(foundIDDRR);
```

2022-01-20 01:45 UTC, eddieh-xlnx approved these changes

2022-01-20 04:25 UTC, merged